data_transformation:
  max_features: 10000
  min_df: 5
  max_df: 0.7
  batch_size: 512

data_eda:
  top_k_ngrams: 20

data_loading:
  batch_size: 64

classic_model:
  n_components: 10
  max_iter: 100

neural_model:
  learning_rate: 0.001
  num_epochs: 50

topic_trainer:
  epochs: 100
